#!/bin/bash

set -e

if [ $# -ne 3 ]; then
  echo "Usage: $0 clientName srcPath destPath"
  exit 1
fi

SSH_CONN=$(rport-tunnel $1)
SSH_DETAILS=(${SSH_CONN//|/ })

if test -d "$2" || test -f "$2"; then
  SRC_PATH=$2
  DST_PATH=scp://${SSH_DETAILS[0]}@${SSH_DETAILS[1]}:${SSH_DETAILS[2]}/$3
else
  SRC_PATH=$3
  DST_PATH=scp://${SSH_DETAILS[0]}@${SSH_DETAILS[1]}:${SSH_DETAILS[2]}/$2
fi

if [ $? -eq 0 ]; then
  echo scp: copying ${SRC_PATH} to ${DST_PATH}
  scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet "${SRC_PATH}" "${DST_PATH}"
fi
