#!/bin/bash

set -e

if [ $# -ne 3 ]; then
  echo "Usage: $0 clientName remotePath localPath"
  exit 1
fi

SSH_CONN=$(rport-tunnel $1)
SSH_DETAILS=(${SSH_CONN//|/ })

if [ $? -eq 0 ]; then
  echo sshfs: mounting ${SSH_DETAILS[0]}@${SSH_DETAILS[1]}:$2 to $3
  sshfs -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet -p ${SSH_DETAILS[2]} "${SSH_DETAILS[0]}@${SSH_DETAILS[1]}:$2" "$3"
fi
